// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Models;

#nullable disable

namespace _1.DAL.Migrations
{
    [DbContext(typeof(BanHangDbContext))]
    partial class BanHangDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1.DAL.Models.ChiTietLaptop", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("money")
                        .HasColumnName("GiaNhap");

                    b.Property<decimal>("Giaban")
                        .HasColumnType("money")
                        .HasColumnName("GiaBan");

                    b.Property<Guid>("IDLaptop")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNsx")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ma");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mota");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("ID");

                    b.HasIndex("IDLaptop");

                    b.HasIndex("IDMauSac");

                    b.HasIndex("IDNsx");

                    b.ToTable("ChiTietLaptop", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.ChucVu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ten");

                    b.HasKey("ID");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.CuaHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenCuaHang");

                    b.HasKey("ID");

                    b.ToTable("CuaHang", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.GiaTri", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDThuocTinh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("ThongSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ThongSo");

                    b.HasKey("ID");

                    b.HasIndex("IDThuocTinh");

                    b.ToTable("GiaTri", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("SdtNguoiNhan")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SdtNguoiNhan");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNguoiNhan");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int")
                        .HasColumnName("TinhTrang");

                    b.HasKey("ID");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdVoucher");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaSauKhiGiam")
                        .HasColumnType("money")
                        .HasColumnName("GiaSauKhiGiam");

                    b.Property<decimal>("GiaTruoc")
                        .HasColumnType("money")
                        .HasColumnName("GiaTruoc");

                    b.Property<Guid>("IDChiTietLapTop")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int")
                        .HasColumnName("TinhTrang");

                    b.HasKey("ID");

                    b.HasIndex("IDChiTietLapTop");

                    b.HasIndex("IDHoaDon");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.Imei", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDChiTietLaptop")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoEmei")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("SoImei");

                    b.HasKey("ID");

                    b.HasIndex("IDChiTietLaptop");

                    b.ToTable("Imei", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.ImeiDaBan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDHoaDonChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoEmei")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("SoImei");

                    b.HasKey("ID");

                    b.HasIndex("IDHoaDonChiTiet");

                    b.ToTable("ImeiDaBan", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.KhachHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HoTen");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("ID");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.Laptop", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ten");

                    b.HasKey("ID");

                    b.ToTable("Laptop", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.MauSac", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ten");

                    b.HasKey("ID");

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HoTen");

                    b.Property<Guid>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCuaHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThai");

                    b.HasKey("ID");

                    b.HasIndex("IdChucVu");

                    b.HasIndex("IdCuaHang");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.Nsx", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ten");

                    b.HasKey("ID");

                    b.ToTable("NhaSanXuat", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.ThuocTinh", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDLaptop")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ten");

                    b.HasKey("ID");

                    b.HasIndex("IDLaptop");

                    b.ToTable("ThuocTinh", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.Voucher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDay")
                        .HasColumnType("datetime")
                        .HasColumnName("EndDay");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("money")
                        .HasColumnName("GiaTri");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ma");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<DateTime>("StartDay")
                        .HasColumnType("datetime")
                        .HasColumnName("StarDay");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten");

                    b.HasKey("ID");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.ChiTietLaptop", b =>
                {
                    b.HasOne("_1.DAL.Models.Laptop", "Laptop")
                        .WithMany()
                        .HasForeignKey("IDLaptop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.MauSac", "MauSac")
                        .WithMany()
                        .HasForeignKey("IDMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.Nsx", "Nsx")
                        .WithMany()
                        .HasForeignKey("IDNsx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");

                    b.Navigation("MauSac");

                    b.Navigation("Nsx");
                });

            modelBuilder.Entity("_1.DAL.Models.GiaTri", b =>
                {
                    b.HasOne("_1.DAL.Models.ThuocTinh", "ThuocTinh")
                        .WithMany()
                        .HasForeignKey("IDThuocTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThuocTinh");
                });

            modelBuilder.Entity("_1.DAL.Models.HoaDon", b =>
                {
                    b.HasOne("_1.DAL.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("IdVoucher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("_1.DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1.DAL.Models.ChiTietLaptop", "ChiTietLaptop")
                        .WithMany()
                        .HasForeignKey("IDChiTietLapTop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("IDHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietLaptop");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("_1.DAL.Models.Imei", b =>
                {
                    b.HasOne("_1.DAL.Models.ChiTietLaptop", "ChiTietLaptop")
                        .WithMany()
                        .HasForeignKey("IDChiTietLaptop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietLaptop");
                });

            modelBuilder.Entity("_1.DAL.Models.ImeiDaBan", b =>
                {
                    b.HasOne("_1.DAL.Models.HoaDonChiTiet", "HoaDonChiTiet")
                        .WithMany()
                        .HasForeignKey("IDHoaDonChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1.DAL.Models.NhanVien", b =>
                {
                    b.HasOne("_1.DAL.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("IdCuaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("CuaHang");
                });

            modelBuilder.Entity("_1.DAL.Models.ThuocTinh", b =>
                {
                    b.HasOne("_1.DAL.Models.Laptop", "Laptop")
                        .WithMany()
                        .HasForeignKey("IDLaptop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");
                });
#pragma warning restore 612, 618
        }
    }
}
